import React from "react";
import { Download, MoreVertical, Info, FileText } from "lucide-react";
import "./RecentReports.css";

export default function RecentReports() {
  const reports = [
    {
      name: "Q3 Funding Summary",
      type: "Funding Analytics",
      generatedBy: "Admin User",
      date: "2025-09-15",
      format: "PDF",
    },
    {
      name: "Investor Activity Aug 2025",
      type: "Investor Activity",
      generatedBy: "System",
      date: "2025-09-30",
      format: "Excel",
    },
    {
      name: "Zakat Compliance Report",
      type: "Zakat Compliance",
      generatedBy: "Admin User",
      date: "2025-10-15",
      format: "PDF",
    },
  ];

  return (
    <div className="min-h-screen flex items-center justify-center px-6 py-10 bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100">
      <div className="w-full max-w-5xl rounded-2xl shadow-lg px-8 py-6 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700">
        {/* Header */}
        <div className="flex justify-between items-start mb-8">
          <div>
            <h2 className="text-xl font-semibold flex items-center gap-2">
              Recent Reports <Info size={16} className="opacity-60" />
            </h2>
            <p className="text-sm mt-1 text-gray-500 dark:text-gray-400">
              Previously generated reports available for download
            </p>
          </div>
        </div>

        {/* Filters */}
        <div className="flex flex-wrap md:flex-nowrap items-center gap-4 mb-6">
          <select className="h-[42px] px-3 rounded-lg border text-sm bg-gray-50 dark:bg-gray-700 border-gray-300 dark:border-gray-600 text-gray-800 dark:text-gray-200 focus:outline-none focus:ring-2 focus:ring-gray-300 dark:focus:ring-gray-500">
            <option>Status</option>
          </select>

          <div className="flex-1">
            <input
              type="text"
              placeholder="Search reports..."
              className="search-input"
            />
          </div>
        </div>

        {/* Table */}
        <div className="overflow-x-auto rounded-xl border border-gray-200 dark:border-gray-700">
          <table className="w-full text-sm border-collapse">
            <thead className="bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300">
              <tr>
                <th className="text-left px-6 py-3 font-medium">REPORT NAME</th>
                <th className="text-left px-6 py-3 font-medium">TYPE</th>
                <th className="text-left px-6 py-3 font-medium">GENERATED BY</th>
                <th className="text-left px-6 py-3 font-medium">DATE</th>
                <th className="text-left px-6 py-3 font-medium">FORMAT</th>
                <th className="text-left px-6 py-3 font-medium">ACTIONS</th>
              </tr>
            </thead>
            <tbody>
              {reports.map((r, i) => (
                <tr
                  key={i}
                  className="border-t border-gray-100 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-750 transition-colors"
                >
                  <td className="px-6 py-4 flex items-center gap-2">
                    <span className="inline-flex items-center justify-center w-6 h-6 rounded-md bg-gray-200 dark:bg-gray-600">
                      <FileText size={14} />
                    </span>
                    <span className="font-medium">{r.name}</span>
                  </td>
                  <td className="px-6 py-4">{r.type}</td>
                  <td className="px-6 py-4">{r.generatedBy}</td>
                  <td className="px-6 py-4">{r.date}</td>
                  <td className="px-6 py-4">
                    <span className="px-3 py-[3px] rounded-md text-xs font-medium bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300">
                      {r.format}
                    </span>
                  </td>
                  <td className="px-6 py-3 flex items-center gap-2">
                    <button className="action-btn" title="Download Report">
                      <Download size={15} strokeWidth={1.8} />
                    </button>
                    <button className="action-btn" title="More Options">
                      <MoreVertical size={15} strokeWidth={1.8} />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Pagination */}
        <div className="flex justify-between items-center mt-6 text-sm">
          <p className="text-gray-500 dark:text-gray-400">
            Showing <span className="font-semibold">03</span> / 15 Results
          </p>
          <div className="flex items-center gap-2">
            <button className="page-btn">‹</button>
            <button className="page-btn active">1</button>
            <button className="page-btn">›</button>
          </div>
        </div>

        {/* Footer */}
        <p className="text-center text-xs mt-6 text-gray-400 dark:text-gray-500">
          Market data is updated in real-time. Prices are for reference only and
          may vary across exchanges.
        </p>
      </div>
    </div>
  );
}
