import React from "react";
import { Download, MoreVertical, FileText } from "lucide-react";

export default function RecentReports({ dark }) {
  const reports = [
    {
      name: "Q3 Funding Summary",
      type: "Funding Analytics",
      generatedBy: "Admin User",
      date: "2025-09-15",
      format: "PDF",
    },
    {
      name: "Investor Activity Aug 2025",
      type: "Investor Activity",
      generatedBy: "System",
      date: "2025-09-30",
      format: "Excel",
    },
    {
      name: "Zakat Compliance Report",
      type: "Zakat Compliance",
      generatedBy: "Admin User",
      date: "2025-10-15",
      format: "PDF",
    },
  ];

  const textColor = dark ? "#ffffff" : "#1f2937";
  const borderColor = dark ? "#2f2f2f" : "#e5e7eb";
  const bg = dark ? "#111" : "#fff";

  return (
    <div
      style={{
        display: "flex",
        justifyContent: "center",
        width: "100%",
        padding: "30px 0",
        background: dark ? "#0d0d0d" : "#f8f9fc",
      }}
    >
      <div
        style={{
          width: "100%",
          maxWidth: "950px",
          background: bg,
          padding: "24px",
          borderRadius: "16px",
          border: `1px solid ${borderColor}`,
        }}
      >
        <h2
          style={{
            fontSize: "20px",
            fontWeight: 600,
            marginBottom: "6px",
            color: textColor,
          }}
        >
          Recent Reports
        </h2>
        <p
          style={{
            fontSize: "13px",
            marginBottom: "18px",
            color: dark ? "#bdbdbd" : "#6b7280",
          }}
        >
          Download previously generated reports
        </p>

        <div style={{ overflowX: "auto" }}>
          <table
            style={{
              width: "100%",
              borderCollapse: "collapse",
              fontSize: "14px",
            }}
          >
            <thead>
              <tr
                style={{
                  background: dark ? "#1b1b1b" : "#f3f4f6",
                  color: dark ? "#e5e5e5" : "#374151",
                  textTransform: "uppercase",
                }}
              >
                <th style={{ padding: "14px", textAlign: "left", fontWeight: 600 }}>
                  Report
                </th>
                <th style={{ padding: "14px", textAlign: "left", fontWeight: 600 }}>
                  Type
                </th>
                <th style={{ padding: "14px", textAlign: "left", fontWeight: 600 }}>
                  Generated By
                </th>
                <th style={{ padding: "14px", textAlign: "left", fontWeight: 600 }}>
                  Date
                </th>
                <th
                  style={{
                    padding: "14px",
                    textAlign: "right",
                    fontWeight: 600,
                    width: "70px",
                    whiteSpace: "nowrap",
                  }}
                >
                  Actions
                </th>
              </tr>
            </thead>

            <tbody>
              {reports.map((r, i) => (
                <tr
                  key={i}
                  style={{
                    borderBottom: `1px solid ${borderColor}`,
                    transition: "0.2s",
                    cursor: "pointer",
                  }}
                  onMouseEnter={(e) =>
                    (e.currentTarget.style.background = dark
                      ? "#191919"
                      : "#f9fafb")
                  }
                  onMouseLeave={(e) =>
                    (e.currentTarget.style.background = "transparent")
                  }
                >
                  <td style={{ padding: "14px", color: textColor }}>
                    <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>
                      <FileText
                        size={18}
                        strokeWidth={2}
                        stroke={dark ? "#fff" : "#374151"}
                      />
                      <span style={{ fontWeight: 500 }}>{r.name}</span>
                      <span
                        style={{
                          fontSize: "11px",
                          padding: "3px 8px",
                          borderRadius: "6px",
                          border: `1px solid ${borderColor}`,
                          background: dark ? "#222" : "#fff",
                          color: dark ? "#ddd" : "#374151",
                          fontWeight: 500,
                        }}
                      >
                        {r.format}
                      </span>
                    </div>
                  </td>

                  <td style={{ padding: "14px", color: textColor }}>{r.type}</td>
                  <td style={{ padding: "14px", color: textColor }}>{r.generatedBy}</td>
                  <td style={{ padding: "14px", color: textColor }}>{r.date}</td>

                  <td
                    style={{
                      padding: "14px",
                      textAlign: "right",
                      width: "70px",
                      whiteSpace: "nowrap",
                    }}
                  >
                    <div
                      style={{
                        display: "flex",
                        gap: "6px",
                        justifyContent: "flex-end",
                        alignItems: "center",
                      }}
                    >
                      <Download
                        stroke={dark ? "#fff" : "#374151"}
                        size={16}
                        style={{ cursor: "pointer" }}
                      />

                      <MoreVertical
                        stroke={dark ? "#fff" : "#374151"}
                        size={16}
                        style={{ cursor: "pointer" }}
                      />
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
